name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Does_it_build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check if project builds
        run: ./build

  Tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Catch2
        run: |
          if [ "${runner.os}" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get -y install catch2
          elif [ "${runner.os}" == "macOS" ]; then
          brew install catch2
          fi

      - name: Build project
        run: ./build

      - name: Run tests
        run: |
          cd out/Release/test
          chmod +x run_tests
          ./run_tests

  Code_stats:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get code stats
        run: |
          sudo apt-get install cloc
          cloc src/
